animes = [
    {"name": "Attack on Titan", "rating": 9.1, "release_year": 2013, "number_of_episodes": 98},
    {"name": "Death Note", "rating": 8.9, "release_year": 2006, "number_of_episodes": 37},
    {"name": "Fullmetal Alchemist: Brotherhood", "rating": 9.1, "release_year": 2009, "number_of_episodes": 64},
    {"name": "One Punch Man", "rating": 8.7, "release_year": 2015, "number_of_episodes": 24},
    {"name": "Naruto", "rating": 8.4, "release_year": 2002, "number_of_episodes": 220},
    {"name": "Dragon Ball", "rating": 8.5, "release_year": 1986, "number_of_episodes": 153},
    {"name": "Gurren Lagann", "rating": 8.3, "release_year": 2007, "number_of_episodes": 27},
    {"name": "Cowboy Bebop", "rating": 8.9, "release_year": 1998, "number_of_episodes": 26},
    {"name": "Neon Genesis Evangelion", "rating": 8.5, "release_year": 1995, "number_of_episodes": 26},
    {"name": "Steins;Gate", "rating": 8.8, "release_year": 2011, "number_of_episodes": 24},
    {"name": "My Hero Academia", "rating": 8.3, "release_year": 2016, "number_of_episodes": 113},
    {"name": "Demon Slayer", "rating": 8.6, "release_year": 2019, "number_of_episodes": 55},
    {"name": "Jujutsu Kaisen", "rating": 8.6, "release_year": 2020, "number_of_episodes": 47},
    {"name": "Tokyo Ghoul", "rating": 7.8, "release_year": 2014, "number_of_episodes": 48},
    {"name": "Black Clover", "rating": 8.1, "release_year": 2017, "number_of_episodes": 170},
    {"name": "Bleach", "rating": 8.2, "release_year": 2004, "number_of_episodes": 366},
    {"name": "Sword Art Online", "rating": 7.5, "release_year": 2012, "number_of_episodes": 96},
    {"name": "Mob Psycho 100", "rating": 8.6, "release_year": 2016, "number_of_episodes": 37},
    {"name": "Erased", "rating": 8.5, "release_year": 2016, "number_of_episodes": 12},
    {"name": "Code Geass", "rating": 8.7, "release_year": 2006, "number_of_episodes": 50},
    {"name": "Hunter x Hunter", "rating": 9.0, "release_year": 2011, "number_of_episodes": 148},
    {"name": "Re:Zero", "rating": 8.1, "release_year": 2016, "number_of_episodes": 50},
    {"name": "Vinland Saga", "rating": 8.8, "release_year": 2019, "number_of_episodes": 48},
    {"name": "The Rising of the Shield Hero", "rating": 8.0, "release_year": 2019, "number_of_episodes": 38},
    {"name": "Clannad", "rating": 8.0, "release_year": 2007, "number_of_episodes": 47},
    {"name": "Toradora!", "rating": 8.0, "release_year": 2008, "number_of_episodes": 25},
    {"name": "Your Lie in April", "rating": 8.6, "release_year": 2014, "number_of_episodes": 22},
    {"name": "Parasyte: The Maxim", "rating": 8.3, "release_year": 2014, "number_of_episodes": 24},
    {"name": "No Game No Life", "rating": 7.7, "release_year": 2014, "number_of_episodes": 12},
    {"name": "Psycho-Pass", "rating": 8.2, "release_year": 2012, "number_of_episodes": 41},
    {"name": "Haikyuu!!", "rating": 8.7, "release_year": 2014, "number_of_episodes": 85},
    {"name": "Fairy Tail", "rating": 7.6, "release_year": 2009, "number_of_episodes": 328},
    {"name": "The Promised Neverland", "rating": 8.0, "release_year": 2019, "number_of_episodes": 23},
    {"name": "Made in Abyss", "rating": 8.4, "release_year": 2017, "number_of_episodes": 25},
    {"name": "Noragami", "rating": 7.9, "release_year": 2014, "number_of_episodes": 25},
    {"name": "Akame ga Kill!", "rating": 7.8, "release_year": 2014, "number_of_episodes": 24},
    {"name": "Hellsing Ultimate", "rating": 8.3, "release_year": 2006, "number_of_episodes": 10},
    {"name": "Monster", "rating": 8.7, "release_year": 2004, "number_of_episodes": 74},
    {"name": "Ergo Proxy", "rating": 7.9, "release_year": 2006, "number_of_episodes": 23},
    {"name": "The Tatami Galaxy", "rating": 8.5, "release_year": 2010, "number_of_episodes": 11},
    {"name": "Berserk (1997)", "rating": 8.7, "release_year": 1997, "number_of_episodes": 25},
    {"name": "Baccano!", "rating": 8.3, "release_year": 2007, "number_of_episodes": 16},
    {"name": "Trigun", "rating": 8.2, "release_year": 1998, "number_of_episodes": 26},
    {"name": "Elfen Lied", "rating": 7.9, "release_year": 2004, "number_of_episodes": 13},
    {"name": "Devilman Crybaby", "rating": 7.8, "release_year": 2018, "number_of_episodes": 10},
    {"name": "Great Teacher Onizuka", "rating": 8.6, "release_year": 1999, "number_of_episodes": 43},
    {"name": "Samurai Champloo", "rating": 8.5, "release_year": 2004, "number_of_episodes": 26},
    {"name": "Kaguya-sama: Love is War", "rating": 8.5, "release_year": 2019, "number_of_episodes": 37},
    {"name": "Zankyou no Terror", "rating": 7.9, "release_year": 2014, "number_of_episodes": 11},
    {"name": "Bakuman", "rating": 8.1, "release_year": 2010, "number_of_episodes": 75},
    {"name": "Kaiji: Ultimate Survivor", "rating": 8.2, "release_year": 2007, "number_of_episodes": 26},
    {"name": "Dorohedoro", "rating": 8.1, "release_year": 2020, "number_of_episodes": 12},
    {"name": "91 Days", "rating": 7.7, "release_year": 2016, "number_of_episodes": 12},
    {"name": "Barakamon", "rating": 8.2, "release_year": 2014, "number_of_episodes": 12},
    {"name": "March Comes in Like a Lion", "rating": 8.6, "release_year": 2016, "number_of_episodes": 44},
    {"name": "Anohana: The Flower We Saw That Day", "rating": 8.2, "release_year": 2011, "number_of_episodes": 11},
    {"name": "Nichijou", "rating": 8.5, "release_year": 2011, "number_of_episodes": 26},
    {"name": "Golden Kamuy", "rating": 8.0, "release_year": 2018, "number_of_episodes": 49},
    {"name": "Durarara!!", "rating": 7.8, "release_year": 2010, "number_of_episodes": 60},
    {"name": "The Devil is a Part-Timer!", "rating": 7.6, "release_year": 2013, "number_of_episodes": 13},
    {"name": "Hyouka", "rating": 8.0, "release_year": 2012, "number_of_episodes": 22},
    {"name": "Beastars", "rating": 7.8, "release_year": 2019, "number_of_episodes": 24},
    {"name": "Yuri!!! on Ice", "rating": 7.9, "release_year": 2016, "number_of_episodes": 12},
    {"name": "Ajin: Demi-Human", "rating": 7.6, "release_year": 2016, "number_of_episodes": 26},
    {"name": "Devil Survivor 2", "rating": 7.0, "release_year": 2013, "number_of_episodes": 13},
    {"name": "Future Diary (Mirai Nikki)", "rating": 7.5, "release_year": 2011, "number_of_episodes": 26},
    {"name": "Inuyasha", "rating": 7.9, "release_year": 2000, "number_of_episodes": 167},
    {"name": "Nana", "rating": 8.4, "release_year": 2006, "number_of_episodes": 47},
    {"name": "Serial Experiments Lain", "rating": 8.0, "release_year": 1998, "number_of_episodes": 13},
    {"name": "Kill la Kill", "rating": 7.9, "release_year": 2013, "number_of_episodes": 24},
    {"name": "Wolf's Rain", "rating": 7.9, "release_year": 2003, "number_of_episodes": 30},
    {"name": "Blue Exorcist", "rating": 7.5, "release_year": 2011, "number_of_episodes": 37},
    {"name": "Terror in Resonance", "rating": 7.9, "release_year": 2014, "number_of_episodes": 11},
    {"name": "Fruits Basket (2019)", "rating": 8.6, "release_year": 2019, "number_of_episodes": 63},
    {"name": "Kino's Journey", "rating": 8.4, "release_year": 2003, "number_of_episodes": 13},
    {"name": "School Rumble", "rating": 7.8, "release_year": 2004, "number_of_episodes": 52},
    {"name": "The World God Only Knows", "rating": 7.6, "release_year": 2010, "number_of_episodes": 36},
    {"name": "Chihayafuru", "rating": 8.2, "release_year": 2011, "number_of_episodes": 75},
    {"name": "K-On!", "rating": 7.8, "release_year": 2009, "number_of_episodes": 39},
    {"name": "Bakugan Battle Brawlers", "rating": 6.1, "release_year": 2007, "number_of_episodes": 189},
    {"name": "Bungo Stray Dogs", "rating": 7.8, "release_year": 2016, "number_of_episodes": 61},
    {"name": "A Silent Voice", "rating": 8.2, "release_year": 2016, "number_of_episodes": 1},
    {"name": "Dr. Stone", "rating": 8.1, "release_year": 2019, "number_of_episodes": 49},
    {"name": "Welcome to the NHK", "rating": 8.3, "release_year": 2006, "number_of_episodes": 24},
    {"name": "Kekkai Sensen (Blood Blockade Battlefront)", "rating": 7.6, "release_year": 2015, "number_of_episodes": 24},
    {"name": "Tsukimonogatari", "rating": 7.7, "release_year": 2014, "number_of_episodes": 4},
    {"name": "Katanagatari", "rating": 8.1, "release_year": 2010, "number_of_episodes": 12},
    {"name": "Nisekoi", "rating": 7.0, "release_year": 2014, "number_of_episodes": 32},
    {"name": "SK8 the Infinity", "rating": 8.0, "release_year": 2021, "number_of_episodes": 12},
    {"name": "Angels of Death", "rating": 6.9, "release_year": 2018, "number_of_episodes": 16},
    {"name": "The Ancient Magus' Bride", "rating": 7.7, "release_year": 2017, "number_of_episodes": 24},
    {"name": "Charlotte", "rating": 7.6, "release_year": 2015, "number_of_episodes": 13},
    {"name": "Plastic Memories", "rating": 7.3, "release_year": 2015, "number_of_episodes": 13},
    {"name": "Mahou Shoujo Madoka★Magica", "rating": 8.3, "release_year": 2011, "number_of_episodes": 12},
    {"name": "Tsurezure Children", "rating": 7.5, "release_year": 2017, "number_of_episodes": 12},
    {"name": "Kanata no Astra", "rating": 8.0, "release_year": 2019, "number_of_episodes": 12},
    {"name": "Ascendance of a Bookworm", "rating": 8.1, "release_year": 2019, "number_of_episodes": 37},
    {"name": "How Heavy Are the Dumbbells You Lift?", "rating": 7.3, "release_year": 2019, "number_of_episodes": 12},
    {"name": "The Quintessential Quintuplets", "rating": 7.6, "release_year": 2019, "number_of_episodes": 24},
    {"name": "Hanebado!", "rating": 6.9, "release_year": 2018, "number_of_episodes": 13}
]

